name: nutri_app
description: O intuito desse aplicativo é armazenar a tabela nutricional de diversos alimentos e realizar ações sobre eles.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^4.0.0


  animations: ^1.1.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/

